---
- name: Install lftp
  apt: 
    update_cache: yes
    pkg:
      - lftp
  become: yes
  become_user: root

- name: Make .lftp directory
  file:
    path: ~/.lftp
    state: directory

- name: Put .lftprc
  copy:
    dest: ~/.lftprc
    content: |
      set bmk:save-passwords 1
      set ftp:ssl-auth TLS
      set ftp:ssl-force true
      set ftp:ssl-allow yes
      set ftp:ssl-protect-list yes
      set ftp:ssl-protect-data yes
      set ftp:ssl-protect-fxp yes
