---
- name: Make src dir
  file:
    path: ~/src
    state: directory

- name: Download tarball
  get_url:
    url: https://github.com/jonas/tig/releases/download/tig-2.5.5/tig-2.5.5.tar.gz
    dest: ~/src
    checksum: sha256:24ba2c8beae889e6002ea7ced0e29851dee57c27fde8480fb9c64d5eb8765313

- name: Unarchive tarball
  unarchive:
    src: ~/src/tig-2.5.5.tar.gz
    dest: ~/src
    remote_src: yes

- name: Build tig
  shell: |
    make
    make install
  args:
    chdir: ~/src/tig-2.5.5
