---
- name: Allow user to sudo without password
  copy:
    dest: /etc/sudoers.d/{{ ansible_user_id }}
    content: |
      {{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL
  become: yes
  become_user: root
